# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a10796bd29947f868b38ccb23dd565f1513d53f530a5f55ad0566481cfd1e936a111d80b27b1d3096aa8a3bfe5525f387b056ed749278923ad44cf3a454a19d0

test:
  secret_key_base: d208ee6029ac8182195300baba379abb65d7652207f560259ed5029f5805dbab3a0ca14f8ce8c039362b780340bf868effedae66ea29446b57bb9e2059ca8c80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
