require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PostsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Post. As you add validations to Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:post).attributes
  }

  let(:invalid_attributes) {
    {'title' => ''}
  }

  def parsed_body
    JSON.parse(response.body)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let(:post_instance) { create(:post) }

  describe "GET #index" do
    it "assigns all post_instances as @post_instances" do
      expect(ActiveModel::Serializer::CollectionSerializer).to receive(:new).with([post_instance], each_serializer: PostSerializer).and_call_original

      get :index, params: {}, session: valid_session
    end
  end

  describe "GET #show" do
    it "assigns the requested post_instance as @post_instance" do
      expect(controller).to receive(:find_post) { post_instance }
      # expect(PostSerializer).to receive(:new).with(post_instance).and_call_original
      expect(PostSerializer).to receive(:new).with(post_instance, {:namespace=>nil, :scope=>nil, :scope_name=>:current_user}).and_call_original

      get :show, params: {id: post_instance.to_param}, session: valid_session
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Post" do
        expect {
          post :create, params: {post: valid_attributes}
        }.to change(Post, :count).by(1)
      end

      it 'responds with 201' do
        post :create, params: {post: valid_attributes}, session: valid_session
        expect(response.status).to eq(201)
      end
    end

    context "with invalid params" do
      it 'responds with errors' do
        post :create, params: {post: invalid_attributes}, session: valid_session
        expect(parsed_body['errors']['body']).to be_present
        expect(parsed_body['errors']['title']).to be_present
      end

      it 'responds with 422' do
        post :create, params: {post: invalid_attributes}, session: valid_session
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      it 'responds with 200' do
        put :update, params: { id: post_instance.id, post: valid_attributes}, session: valid_session
        expect(response.status).to eq(200)
      end
    end

    context "with invalid params" do
      it 'responds with errors' do
        put :update, params: { id: post_instance.id, post: invalid_attributes}, session: valid_session
        expect(parsed_body['errors']['title']).to be_present
      end

      it 'responds with 422' do
        put :update, params: { id: post_instance.id, post: invalid_attributes}, session: valid_session
        expect(response.status).to eq(422)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested post_instance" do
      post_instance
      expect {
        delete :destroy, params: {id: post_instance.to_param}, session: valid_session
      }.to change(Post, :count).by(-1)
    end

    it 'responds with 204' do
      delete :destroy, params: {id: post_instance.to_param}, session: valid_session
      expect(response.status).to eq(204)
    end
  end

end
